name: 'action-maven-cli'
description: 'Wrapper for Maven'
inputs:
  args:  # id of input
    description: 'Arguments to pass to Maven'
    required: true
    default: 'World'
  token:
    required: true
  owner:
    required: true
  username:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
  env:
    TOKEN: ${{ inputs.token }}
    USERNAME: ${{ inputs.username }}
    OWNER: ${{ inputs.owner }}
