name: 'action-maven-cli'
description: 'Wrapper for Maven'
inputs:
  args:  # id of input
    description: 'Arguments to pass to Maven'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
